<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-instagram-fill tw-text-35px tw-text-white</name>
   <tag></tag>
   <elementGuidId>938c59cb-4fb0-4e01-95ec-091739be304c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[3]/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#footer-card >> internal:label=&quot;Jo Academy Account on Instagram&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8c163fcf-c071-4759-992c-b9c1cf319910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-instagram-fill tw-text-[35px] tw-text-white </value>
      <webElementGuid>b52e90b9-91a8-4a16-a747-ef8ff354e909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-card&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-justify-between lg:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-2&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-6&quot;]/div[3]/a[1]/i[@class=&quot;ri-instagram-fill tw-text-[35px] tw-text-white&quot;]</value>
      <webElementGuid>38d0922c-553d-45b8-a05f-e3b09290b1fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[3]/div/div[3]/a/i</value>
      <webElementGuid>5ec9312d-cd7a-4a92-9883-b88231c4a170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a/i</value>
      <webElementGuid>d40a18d5-9131-4bd4-9fe3-122a4915bb28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
