<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify Social Media</name>
   <tag></tag>
   <elementGuidId>1d8745ba-09b3-4466-a3b1-3dc7c454635c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[3]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0bf02126-cd18-45b8-b0a5-a332861fad83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-text-[16px] tw-text-white</value>
      <webElementGuid>32103d3b-1d5d-4746-a5df-61b7b8e0b19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>صفحاتنا على مواقع التواصل الاجتماعي</value>
      <webElementGuid>e113a3c7-c795-4bfc-95bd-2200c4bcbe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-card&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-justify-between lg:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-2&quot;]/h3[@class=&quot;tw-text-[16px] tw-text-white&quot;]</value>
      <webElementGuid>367ee616-b298-43c8-ade8-a9b66852c248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[3]/h3</value>
      <webElementGuid>a4644db5-9368-4ed3-be1a-88e46e195f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::h3[1]</value>
      <webElementGuid>6a5c8ca1-dc7a-4644-8686-533a71b0f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التطبيق لنظام'])[2]/following::h3[2]</value>
      <webElementGuid>828c57c9-8bf6-4dd2-8072-a145052ca270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي']/parent::*</value>
      <webElementGuid>deb782e3-5332-40c8-8b21-5323cd6c1d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h3</value>
      <webElementGuid>5b7fd8e2-31af-4557-821c-9fc7a700f670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'صفحاتنا على مواقع التواصل الاجتماعي' or . = 'صفحاتنا على مواقع التواصل الاجتماعي')]</value>
      <webElementGuid>da12ae0a-8432-4347-8dc6-f628878a3f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
