<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close</name>
   <tag></tag>
   <elementGuidId>91e9408c-e4cc-448e-ada9-fac366c1582d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:ri:&quot;]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tw-absolute.tw-bg-white</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
