<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>3e77d037-ef1d-4fb6-a0c3-4ae6827802f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1m:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;لطفاً! عليك تسجيل الدخول أولاً&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ef121e7-c5a0-4847-ae65-de48b0ffee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9f52242e-611b-4d24-80e9-d77abb5583c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r1m:</value>
      <webElementGuid>613156b9-8f77-4973-8be8-a3217da219aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-:r1o:</value>
      <webElementGuid>136d7a53-a18e-45bd-b7bd-b20351f508a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-:r1n:</value>
      <webElementGuid>74601063-4fb5-46ad-9ebd-6c59a45562dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>2a8f71d8-dcc9-4121-a241-1f3a65415f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>0b9fd7d0-ce0b-445b-b0aa-59a40c03d71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!tw-pointer-events-auto sm:max-w-[425px] tw-gap-[40px] tw-z-[10000] tw-fixed tw-left-[50%] tw-top-[50%] tw-z-50 tw-grid tw-w-full tw-max-w-lg tw-translate-x-[-50%] tw-translate-y-[-50%] tw-gap-4 tw-rounded-[10px] tw-fixed tw-left-[50%] tw-top-[50%] tw-z-50 tw-grid tw-w-full tw-max-w-lg tw-translate-x-[-50%] tw-translate-y-[-50%] tw-gap-4 tw-rounded-[10px] tw-border tw-bg-white tw-p-6 tw-shadow-lg tw-duration-200r tw-bg-white tw-p-6 tw-shadow-lg tw-duration-200 tw-animate-in tw-fade-in-0 tw-zoom-in-95 tw-slide-in-from-left-1/2 tw-slide-in-from-top-[48%]</value>
      <webElementGuid>0108f247-9862-4828-9e5f-13fd921785cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e6d2282b-0493-45d1-8c3f-12f6ebe72817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>لطفاً! عليك تسجيل الدخول أولاًحتى تتمكن من إتمام هذه العملية يجب أن تقوم بانشاء حساب في جواكاديميانشاء حساب جديدتسجيل الدخولClose</value>
      <webElementGuid>a48e4d50-1e38-4b7a-8673-201befaff34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1m:&quot;)</value>
      <webElementGuid>c45fb0ee-cb9a-496d-b118-3382e40b5b8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1m:']</value>
      <webElementGuid>50189782-2d9a-48ab-8a4e-6495b6a7167a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[10]</value>
      <webElementGuid>d7a485f8-6548-4cbf-9922-7b062473681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e70cd3a4-c53e-4e3f-b024-d34bb0b59e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-:r1m:' and (text() = 'لطفاً! عليك تسجيل الدخول أولاًحتى تتمكن من إتمام هذه العملية يجب أن تقوم بانشاء حساب في جواكاديميانشاء حساب جديدتسجيل الدخولClose' or . = 'لطفاً! عليك تسجيل الدخول أولاًحتى تتمكن من إتمام هذه العملية يجب أن تقوم بانشاء حساب في جواكاديميانشاء حساب جديدتسجيل الدخولClose')]</value>
      <webElementGuid>4f37cb81-7fc2-477a-8520-93fbffc6f5ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
