<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home page</name>
   <tag></tag>
   <elementGuidId>e1d3c860-a404-4d2e-b9e9-e1e9cb8344e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar-card']/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.tw-h-full.tw-w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;JO LOGO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cae4dac8-e491-4e11-b077-d8fbf0563f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JO LOGO</value>
      <webElementGuid>07520f35-5af6-48e8-a93a-403e2f8af1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7efefebe-bd1b-4ad8-b5fc-8956a369d875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>464</value>
      <webElementGuid>6b474db8-cdf2-4f03-91af-5ee88bc1caa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>2e8b25e9-f7b7-4b1a-8392-3f2b260d95eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c12146c2-e45e-4283-89e5-87c8a9a642a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ee14f18-9db1-4ae7-84fc-8c2d5bd286b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-h-full tw-w-full</value>
      <webElementGuid>a2ee144e-12ba-45c0-853b-f3b7ef546e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/Animation-Ramadan-JO-slow-2.94b9f588.gif</value>
      <webElementGuid>74ffd917-3eb2-4aad-ad0b-a8a18ab2ee07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-card&quot;)/div[@class=&quot;tw-flex tw-h-full tw-items-center tw-justify-between tw-gap-4 tw-px-4 lg:tw-px-8&quot;]/div[@class=&quot;tw-flex tw-h-full tw-items-center tw-justify-center false&quot;]/a[@class=&quot;tw-flex !tw-min-w-[120px] max-md:tw-px-4&quot;]/div[@class=&quot;tw-max-h-[40px] tw-w-full tw-max-w-[200px]&quot;]/img[@class=&quot;tw-h-full tw-w-full&quot;]</value>
      <webElementGuid>5935f6ad-3774-4f7e-a94b-2914998f6b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-card']/div/div/a/div/img</value>
      <webElementGuid>0921c2bb-a512-4ff1-bb72-40599a5b9614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='JO LOGO']</value>
      <webElementGuid>9a9a4a4a-c6f9-4306-b369-d591db109852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3516f544-e07c-458e-91a0-5910a99ef3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'JO LOGO' and @src = '/_next/static/media/Animation-Ramadan-JO-slow-2.94b9f588.gif']</value>
      <webElementGuid>e5362e2e-a51a-4e6f-8af4-53e17dd66db0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
