<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no_option_sub_category</name>
   <tag></tag>
   <elementGuidId>3a7989bd-dcad-4e03-9b6b-c4220000feee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[aria-multiselectable='false']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
