<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Program_From_Landing_Page</name>
   <tag></tag>
   <elementGuidId>545129e8-9796-4ac0-ab87-e2947fd8e0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label='اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d22e073-060f-437d-961f-5710652dc9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي</value>
      <webElementGuid>46094448-4fbd-46a1-9339-64963ed99139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e3a8ffaa-92f8-4eb0-8500-1fbc109e10c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d994bfd8-cd9a-4543-975a-375dc68fa5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>230</value>
      <webElementGuid>f96e88b6-1f7f-46ca-8ec0-3577e99ae5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e2b7bc0b-9541-4521-93dc-1ca9d11df8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0d40272a-2bc8-4356-bc62-ed5cf6288529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-h-full tw-w-full max-sm:tw-h-[134px] max-sm:tw-w-[72px] sm:tw-h-[134px] sm:tw-w-[72px] md:tw-h-[245px] md:tw-w-full</value>
      <webElementGuid>ff431d8b-ed92-4702-994f-112f92450c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://admin.joacademy.net/uploads/6723/2-tawjihi.png</value>
      <webElementGuid>497af455-17a7-4452-8490-de2bfcadf046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/div[@class=&quot;tw-z-[1000]  md:tw-mt-8 md:tw-max-h-none md:tw-max-w-none&quot;]/img[@class=&quot;tw-h-full tw-w-full max-sm:tw-h-[134px] max-sm:tw-w-[72px] sm:tw-h-[134px] sm:tw-w-[72px] md:tw-h-[245px] md:tw-w-full&quot;]</value>
      <webElementGuid>5a8285b7-54c6-49ab-8833-0ab2b99b6415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/div/img</value>
      <webElementGuid>cccee16a-02bf-40cc-8079-99f2bde0dd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي']</value>
      <webElementGuid>fb47227c-9985-4e29-85de-f0f2341219ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8c4d10e3-c999-4c2c-90f7-60199cc3882f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي' and @src = 'https://admin.joacademy.net/uploads/6723/2-tawjihi.png']</value>
      <webElementGuid>f4abd19b-eb56-4a6b-a2aa-c176d3498aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
