<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_JOACADEMY</name>
   <tag></tag>
   <elementGuidId>90c14025-a126-4f66-b0ac-e2f62dfa62de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.AfwdI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d1360d2-e05d-40f3-b97e-8857172a9528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AfwdI</value>
      <webElementGuid>41ceefe1-2b09-4fa7-bbff-7ca4cd7e568c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>cc31d351-e33f-410a-be89-b4cd7479c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JOACADEMY</value>
      <webElementGuid>0187a749-ef0e-4eb5-bf23-73fdac27f5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf Czez9d&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;kFwPee&quot;]/div[1]/div[@class=&quot;tU8Y5c&quot;]/div[1]/div[@class=&quot;dzkqwc&quot;]/div[@class=&quot;wkMJlb YWi3ub&quot;]/c-wiz[1]/div[@class=&quot;hnnXjf&quot;]/div[@class=&quot;Il7kR&quot;]/div[@class=&quot;RhBWnf&quot;]/div[1]/div[@class=&quot;Fd93Bb ynrBgc xwcR9d&quot;]/h1[1]/span[@class=&quot;AfwdI&quot;]</value>
      <webElementGuid>392a8cb4-78df-421b-981d-b8cb0901a51e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      <webElementGuid>5c2e4c71-cb1d-46d5-8305-24aa329d22e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kids'])[3]/following::span[1]</value>
      <webElementGuid>8e212306-b72f-47e2-a640-a9d4dada906d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books'])[3]/following::span[1]</value>
      <webElementGuid>adc6daa9-0930-49fb-a45b-e288cdbb36b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JoAcademy Group'])[1]/preceding::span[1]</value>
      <webElementGuid>bf0a57da-125e-48bb-a091-ecf10fa4866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Downloads'])[1]/preceding::span[2]</value>
      <webElementGuid>a955f57b-4297-4557-974a-74cd19d47bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JOACADEMY']/parent::*</value>
      <webElementGuid>d48b3f34-8246-4343-98e7-fa77e3c5d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>0b81534d-d61a-469e-839c-26e7257cdb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'JOACADEMY' or . = 'JOACADEMY')]</value>
      <webElementGuid>94132c6f-da81-41b6-bc7b-62e267d9af0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
