<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WINDOWS</name>
   <tag></tag>
   <elementGuidId>31f2a80e-b830-41bb-b639-5bc2fdbb4b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[2]/div/div/a[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;التطبيق لنظام WINDOWS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9847345e-1b8f-4611-ad44-742221dc7def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!tw-w-37 tw-mx-0 tw-my-6 tw-flex tw-flex-row tw-items-center tw-justify-between tw-rounded-lg tw-bg-white tw-px-3 tw-py-1 tw-text-blue-950</value>
      <webElementGuid>4ed9f4f3-ee24-486c-a73f-60e6be91f69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>التطبيق لنظامWINDOWS</value>
      <webElementGuid>007dd512-138e-48e3-aadb-52a9cb4b7c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-card&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-justify-between lg:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-2&quot;]/div[1]/div[@class=&quot;tw-flex tw-items-center tw-justify-center max-sm:tw-flex-col sm:tw-gap-10&quot;]/a[2]/div[@class=&quot;!tw-w-37 tw-mx-0 tw-my-6 tw-flex tw-flex-row tw-items-center tw-justify-between tw-rounded-lg tw-bg-white tw-px-3 tw-py-1 tw-text-blue-950&quot;]</value>
      <webElementGuid>de4f6eb4-1148-4e1d-bbca-461435e98b9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer-card']/div[2]/div[2]/div/div[2]/div/div/a[2]/div</value>
      <webElementGuid>804e616c-5cc1-40bb-8530-5cc9c20e3c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAC'])[1]/following::div[1]</value>
      <webElementGuid>c8cc3afc-28a3-46b8-9d2c-34b868a82353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التطبيق لنظام'])[1]/following::div[1]</value>
      <webElementGuid>54a454db-753e-47e9-aa11-a6530f90d689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]/div</value>
      <webElementGuid>f21cb126-2238-4696-9f59-974917086dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'التطبيق لنظامWINDOWS' or . = 'التطبيق لنظامWINDOWS')]</value>
      <webElementGuid>d66db614-2b5b-4dbb-8f0b-a4a7240ccc35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
