<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-close-line tw-text-3xl</name>
   <tag></tag>
   <elementGuidId>e274d602-6fc5-4655-b9d6-23b8350d9092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-close-line.tw-text-3xl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rb:']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e81e6ae-6094-4471-a973-c70488f384de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-line tw-text-3xl</value>
      <webElementGuid>e618471e-4b48-482f-838c-f36c9f2d80e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:&quot;)/div[@class=&quot;tw-absolute tw-left-2 tw-top-2 tw-flex tw-h-12 tw-w-12 tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-font-extrabold tw-text-[#262d3e] tw-shadow-md&quot;]/i[@class=&quot;ri-close-line tw-text-3xl&quot;]</value>
      <webElementGuid>38bc4acd-bafa-45f3-b94d-e85c66f951d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rb:']/div/i</value>
      <webElementGuid>ead83141-382d-4b3e-8458-6695a6211708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>82987213-905a-43a6-9405-1e11514c99b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
