<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button homepage</name>
   <tag></tag>
   <elementGuidId>3f6d0662-3bd7-4b07-a6f4-1af34c750d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/main/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;الرئيسية&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af63c2e3-860e-49ff-ac1b-8db47c451e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold colors_color-grey__4ONqO tw-duration-1 tw-ease tw-rounded-[10px] tw-px-[5px] tw-transition hover:tw-bg-[#f3f3f3]</value>
      <webElementGuid>004cfe7e-5af2-4ef7-8995-682f9c29909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home/tawjihi</value>
      <webElementGuid>8d7e4ca6-3fa6-4a0a-97d4-5186a634aa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الرئيسية</value>
      <webElementGuid>ba550322-b9f4-46d0-8d83-94dbca2ecc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-w-full tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/main[@class=&quot;tw-mt-4 tw-pb-[20px] sm:tw-pb-[50px]&quot;]/nav[1]/ul[@class=&quot;tw-m-0 tw-flex tw-flex-wrap tw-items-center tw-px-0 tw-capitalize&quot;]/li[@class=&quot;tw-flex tw-items-center tw-text-[12px] md:tw-text-[16px]&quot;]/a[@class=&quot;bold colors_color-grey__4ONqO tw-duration-1 tw-ease tw-rounded-[10px] tw-px-[5px] tw-transition hover:tw-bg-[#f3f3f3]&quot;]</value>
      <webElementGuid>2cc6aced-532f-4571-b9c7-a4baaf806a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/main/nav/ul/li/a</value>
      <webElementGuid>cf4c5f07-2b79-486e-9a56-e715400ec411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'الرئيسية')]</value>
      <webElementGuid>b7759dc9-0943-435e-ae15-35f5ef8867c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل'])[1]/following::a[6]</value>
      <webElementGuid>0ddb3ddf-de7c-479a-bdea-1f3f4cd2367b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دخول'])[1]/following::a[7]</value>
      <webElementGuid>b22fe5b9-0cca-4229-8449-4b5216e46efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[2]/preceding::a[1]</value>
      <webElementGuid>0019c63a-5e11-440a-8648-71b71e2b7644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[3]/preceding::a[1]</value>
      <webElementGuid>02349f6f-0ac0-445b-baee-20880add5d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الرئيسية']/parent::*</value>
      <webElementGuid>4ab4d00f-e495-478e-894e-ceaaf024a420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/home/tawjihi')])[2]</value>
      <webElementGuid>852a70bd-d724-4c1d-ab7e-cbb01d44267e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>c67c0c5f-da24-4306-be64-4ebd7c559afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home/tawjihi' and (text() = 'الرئيسية' or . = 'الرئيسية')]</value>
      <webElementGuid>46a636a9-1a11-4243-afdd-31ce95621e2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
