<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <elementGuidId>d4b84577-0391-4527-82fa-05efd6c7874f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;تسجيل الدخول&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e20ebb5-844d-4ef9-b093-20546ba0817b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[15px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px]</value>
      <webElementGuid>88169631-29f5-4dc4-9f91-b30b254503ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f633290b-fc96-4cd6-be06-3f7764a1c464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>1167d3b9-1645-48ab-b76c-96cef4693971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1o:&quot;)/div[@class=&quot;tw-flex tw-flex-col-reverse sm:tw-flex-row sm:tw-justify-end tw-flex tw-flex-col tw-flex-nowrap tw-justify-center tw-gap-[10px] sm:tw-flex sm:tw-flex-row sm:tw-flex-wrap sm:tw-flex-nowrap sm:tw-gap-[10px]&quot;]/div[@class=&quot;tw-w-full md:tw-m-auto md:tw-max-w-[250px]&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[15px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px]&quot;]</value>
      <webElementGuid>b9a5cf48-0fc2-4569-9957-bc8fc35c178e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>8e6037f1-a79c-41c0-b470-bee0695f2b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1o:']/div[2]/div[2]/button</value>
      <webElementGuid>70db43e1-c074-4b3f-bf04-f8689215ccab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشاء حساب جديد'])[1]/following::button[1]</value>
      <webElementGuid>f58fa2e2-a0b5-4635-bc77-63b2178ad9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لطفاً! عليك تسجيل الدخول أولاً'])[1]/following::button[2]</value>
      <webElementGuid>1a584ac3-6056-4b99-92ed-3c3b4d43bb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>b2db5418-4c5f-4a68-9b87-667d8cb11590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تسجيل الدخول']/parent::*</value>
      <webElementGuid>a5ad75b9-f981-42ba-9028-e9fd447947aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>34913d41-7785-4dd1-a765-bbc78aca0ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>1b5d9029-0e6c-44bb-a066-ab5c979d852b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
