<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>empty_otp_validation</name>
   <tag></tag>
   <elementGuidId>39a88e64-0f34-4b84-a720-d77be40ced72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[dir='rtl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':ra:-form-item-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
