<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__otp</name>
   <tag></tag>
   <elementGuidId>9b4e5b92-261d-432b-b4a6-cba686c9b597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[data-input-otp=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=':ra:-form-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>191cd12c-faa6-4132-aa38-62e6d6555d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>0e519677-b9eb-452e-abfb-1898ae8cf758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled:tw-cursor-not-allowed</value>
      <webElementGuid>4914aae0-4bb4-495b-bd0c-b846771f31be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pin</value>
      <webElementGuid>ddcb735d-8eec-47ff-8fee-427acb14ec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ra:-form-item</value>
      <webElementGuid>0a3cfea2-a77d-4eab-bb97-49c59b17dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:ra:-form-item-description</value>
      <webElementGuid>244dbe4d-b7ae-488d-97ed-d373b403dcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b434c7f-cb09-42a3-88d7-c0e5bc0023f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2daa043-d336-4fff-9798-a76e637a82fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b27802a4-4559-4965-8d05-d62dbcf86e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d+$</value>
      <webElementGuid>b64bef42-77fb-44e1-9141-a63a60ef7333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ba28680c-86ce-417b-bea4-fa5393ccaf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7fe44be7-2f0a-4f99-b45c-62b212e47904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mss</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02a076bd-d0b6-49d4-9f45-39c368a64160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mse</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f95ba43-e9cb-45ac-accd-ec18d4a08eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ra:-form-item&quot;)</value>
      <webElementGuid>c706a0c8-4e9b-4df9-99ba-de604a5b155a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':ra:-form-item']</value>
      <webElementGuid>2402f5f9-bd19-4aae-b51c-baf92a760d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/section/form/div/div/div[2]/input</value>
      <webElementGuid>dd7e9d3e-0c12-429a-9609-36cac98c1ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>934a83fa-fa59-4e22-9255-aa8e67819ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pin' and @id = ':ra:-form-item']</value>
      <webElementGuid>7a792b31-ec8a-4c74-8009-132112836dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
