<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp_validation</name>
   <tag></tag>
   <elementGuidId>009c82c4-acfd-4e5a-a799-8dd1595c9d7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;:rb:-form-item-message&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>19c9614a-57ba-466d-8c80-4e834c405ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ra:-form-item-message</value>
      <webElementGuid>040d9d2c-469c-43d1-a221-e890c52b6d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-text-sm tw-font-medium tw-text-red-500 dark:tw-text-red-900</value>
      <webElementGuid>8db07a16-66ed-481b-aab3-b2afae23d90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>942322b5-9cad-41f7-a6de-4a161f063449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الرمز أو رقم الهاتف المحمول غير صالح</value>
      <webElementGuid>0fcba563-739d-450c-98c4-a1281256ec17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ra:-form-item-message&quot;)</value>
      <webElementGuid>3ec6b1fe-67e1-4902-9374-2f09c940b54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':ra:-form-item-message']</value>
      <webElementGuid>2d33b0fc-ac43-4e45-a306-c9f17bb3ed4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/section/form/div/p</value>
      <webElementGuid>59973567-03a2-4dd3-880b-ede227950ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل'])[1]/following::p[3]</value>
      <webElementGuid>dafa92b2-9406-4664-82a9-67a27aff612c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دخول'])[1]/following::p[3]</value>
      <webElementGuid>2cd05194-1547-47bd-a250-5702240fa706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ارسل مرة أخرى'])[1]/preceding::p[1]</value>
      <webElementGuid>70d5be6d-4475-48ac-8e80-56aabf85ff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أرسل'])[1]/preceding::p[1]</value>
      <webElementGuid>eb07f684-61ea-4a4b-902c-02bc5f7649ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الرمز أو رقم الهاتف المحمول غير صالح']/parent::*</value>
      <webElementGuid>13c0258c-4d62-4d78-be79-a8daec255c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>6b88899c-bb6e-4c55-b1c3-e71486e822ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':ra:-form-item-message' and (text() = 'الرمز أو رقم الهاتف المحمول غير صالح' or . = 'الرمز أو رقم الهاتف المحمول غير صالح')]</value>
      <webElementGuid>f0d0c814-bd2a-43ef-9a8b-625c5e396720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
