<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp_validation</name>
   <tag></tag>
   <elementGuidId>009c82c4-acfd-4e5a-a799-8dd1595c9d7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':ra:-form-item-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f2779e43-00c5-4d99-8e3f-7bea17f76f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ra:-form-item-message</value>
      <webElementGuid>70258dcb-42a5-4f97-9137-abd18d0fd14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-text-sm tw-font-medium tw-text-red-500 dark:tw-text-red-900</value>
      <webElementGuid>d25126cd-0391-4ea0-b449-c6da27031710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>1094992f-33a8-46e6-94c9-fa769ed4d82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الرمز أو رقم الهاتف المحمول غير صالح</value>
      <webElementGuid>100aa7b4-d8c7-4749-a6b7-607fb3e4eedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ra:-form-item-message&quot;)</value>
      <webElementGuid>f465d6c6-b9c2-4e3c-ac60-a373d22e55ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':ra:-form-item-message']</value>
      <webElementGuid>529e2502-baff-4ac4-808b-4bec1ca8ef6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/section/form/div/p</value>
      <webElementGuid>394347a3-2d33-4240-aee8-8924c08be49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل'])[1]/following::p[3]</value>
      <webElementGuid>2d47b2bc-99fe-4c8c-9640-4bf86cd42cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دخول'])[1]/following::p[3]</value>
      <webElementGuid>2f78f5bc-3b6d-4272-a244-8450aa7dffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ارسل مرة أخرى'])[1]/preceding::p[1]</value>
      <webElementGuid>81a766c4-954c-4c98-b6ba-4f07799345cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أرسل'])[1]/preceding::p[1]</value>
      <webElementGuid>4a2af999-42a7-4133-9cbc-754adeba9ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الرمز أو رقم الهاتف المحمول غير صالح']/parent::*</value>
      <webElementGuid>216c4376-003d-4e4d-9cb4-35c36665898b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>6744c066-629d-4936-9dcd-9fe09fe318bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':ra:-form-item-message' and (text() = 'الرمز أو رقم الهاتف المحمول غير صالح' or . = 'الرمز أو رقم الهاتف المحمول غير صالح')]</value>
      <webElementGuid>a57e219d-c53b-4dbf-9e16-349ab0fe590a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
