<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Teacher_to_Fav_Heart</name>
   <tag></tag>
   <elementGuidId>138754ad-c8c2-41d4-a36e-1398890e17ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/div[2]/div/div/a/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ماهر نجم  ماهر نجم ماهر نجم معلم مادة الكيمياء بخبرة تزيد عن 31 عام في مجال التدريس الثانوي و العديد من مدارس القطاع الخاص و الحكومي والمراكز الثقافية المنتشرة في المملكة تخرج على يديه العديد من أوائل المملكة user-add متابعة الاستاذ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9181730c-9c4c-4017-b7a4-3920ad8d8348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-heart-3-fill transition tw-absolute tw-end-5 tw-top-4 tw-text-[24px] tw-duration-300 tw-text-[#cbcbcb]</value>
      <webElementGuid>1053d099-3518-43b4-97cd-ef6a51cce86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/main[@class=&quot;tw-mt-4 tw-pb-[20px] sm:tw-pb-[50px]&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-stretch tw-justify-center tw-gap-4 tw-py-4&quot;]/div[@class=&quot;tw-grid tw-grid-cols-1 tw-gap-4 tw-px-4 md:tw-grid-cols-2 lg:tw-grid-cols-3 xl:tw-grid-cols-4&quot;]/div[1]/a[@class=&quot;tw-relative tw-cursor-pointer&quot;]/div[@class=&quot;tw-flex tw-max-h-[20rem] tw-min-h-[20rem] tw-flex-1 tw-flex-col  tw-rounded-lg tw-bg-white tw-p-5 tw-shadow hover:tw-shadow-[0_10px_10px_0_rgba(0,0,0,0.2)]&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center&quot;]/i[@class=&quot;ri-heart-3-fill transition tw-absolute tw-end-5 tw-top-4 tw-text-[24px] tw-duration-300 tw-text-[#cbcbcb]&quot;]</value>
      <webElementGuid>51e0c89d-f00a-4f4c-9722-6a5398bd074e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/div[2]/div/div/a/div/div/i</value>
      <webElementGuid>1fcf0a37-3573-46b7-8fb0-2d31a253e77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/i</value>
      <webElementGuid>d9d2bc4b-6a53-40f8-83c2-c623ed2de206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
