<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Success_msg_Teacher_Profile_Copied</name>
   <tag></tag>
   <elementGuidId>3a00707a-f55c-475e-ae22-cb66486afd1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'تم نسخ الرابط' or . = 'تم نسخ الرابط')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.semi-bold.tw-text-sm.tw-opacity-90</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6760f1e-9a8c-4ef4-b064-98e3ca0f7517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-text-sm tw-opacity-90</value>
      <webElementGuid>b1f57004-1de2-4c39-8245-6c9f3e1f6157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تم نسخ الرابط</value>
      <webElementGuid>b3f6c689-6b40-4c93-9392-e4542815d6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/ol[@class=&quot;tw-fixed tw-top-0 tw-z-[35000000] tw-flex tw-max-h-screen tw-w-full tw-flex-col-reverse tw-p-4 sm:tw-bottom-0 sm:tw-right-0 sm:tw-top-auto sm:tw-flex-col md:tw-max-w-[420px]&quot;]/li[@class=&quot;tw-group tw-pointer-events-auto tw-relative tw-flex tw-w-full tw-items-center tw-justify-between tw-space-x-4 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-p-6 tw-pr-8 tw-shadow-lg tw-transition-all data-[swipe=cancel]:tw-translate-x-0 data-[swipe=end]:tw-translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:tw-translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:tw-transition-none data-[state=open]:tw-animate-in data-[state=closed]:tw-animate-out data-[swipe=end]:tw-animate-out data-[state=closed]:tw-fade-out-80 data-[state=closed]:tw-slide-out-to-right-full data-[state=open]:tw-slide-in-from-top-full data-[state=open]:sm:tw-slide-in-from-bottom-full dark:tw-border-slate-800 tw-destructive tw-group tw-border-[#00CE7C] tw-bg-[#00CE7C] tw-text-slate-50 dark:tw-border-[#00CE7C] dark:tw-bg-[#00CE7C] dark:tw-text-slate-50&quot;]/div[@class=&quot;tw-grid tw-gap-1 tw-text-start&quot;]/div[@class=&quot;semi-bold tw-text-sm tw-opacity-90&quot;]</value>
      <webElementGuid>1a478d87-e44a-44a3-9437-c7c02399489a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/ol/li/div/div</value>
      <webElementGuid>6f7e3f75-a0d5-4870-9f19-0478fe91d587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[9]</value>
      <webElementGuid>9ca6bc10-4dde-4378-80bd-8ba1d4a00ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::div[10]</value>
      <webElementGuid>cc77e306-10f9-4278-b5f9-137bcb34d046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تم نسخ الرابط']/parent::*</value>
      <webElementGuid>c5507046-cf26-46e9-824e-33e6ad7edab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>2f48ccfe-63e1-4d75-bd48-3fb26ad4d4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'تم نسخ الرابط' or . = 'تم نسخ الرابط')]</value>
      <webElementGuid>b58a6eed-af67-41dd-b8aa-012b7f062c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
