<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>5d919e92-5d9e-4adb-a2e9-5a282e751f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='primary'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71fa29fb-74f0-459b-9ced-e0dde6cf44f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorDarkblue__SQifS tw-rounded-[10px] tw-cursor-pointer !tw-h-[44px]</value>
      <webElementGuid>6ddb2f0f-45c5-4651-a708-2bd1f610b4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f27f5211-1927-4d8d-9ba1-2852b8ec700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نشر</value>
      <webElementGuid>63b890d5-fb3b-49d6-ac08-edbe7843557d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;md:tw-p-5&quot;]/div[@class=&quot;tw-mt-2&quot;]/div[@class=&quot;tw-relative tw-top-[-4px] tw-pt-8&quot;]/div[@class=&quot;ant-col ant-col-rtl css-14i19y2&quot;]/div[@class=&quot;ant-row ant-row-center ant-row-middle ant-row-rtl  shared_full-width__6Fhsp css-14i19y2&quot;]/div[@class=&quot;ant-spin-nested-loading css-14i19y2&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-row ant-row-rtl css-14i19y2&quot;]/div[@class=&quot;shared_full-width__6Fhsp shared_margin-column-half-rem__cGLZG&quot;]/div[@class=&quot;tw-mb-4  tw-rounded-xl tw-border tw-border-gray-100 tw-bg-white tw-px-10 tw-py-8 tw-transition-all tw-duration-300 hover:tw-shadow-md sm:tw-mb-0 sm:tw-px-6 sm:tw-py-4 tw-cursor-pointer&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-between sm:tw-items-center md:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-end tw-justify-center tw-gap-4&quot;]/div[@class=&quot;tw-w-full tw-text-[12px] tw-font-semibold md:tw-w-fit&quot;]/div[@class=&quot;tw-flex tw-h-full tw-w-full tw-items-center tw-justify-end tw-gap-3 tw-text-[12px] tw-font-semibold tw-text-gray-500 sm:tw-mt-3&quot;]/div[@class=&quot;tw-h-[44px] !tw-w-[140px]&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorDarkblue__SQifS tw-rounded-[10px] tw-cursor-pointer !tw-h-[44px]&quot;]</value>
      <webElementGuid>04b34f3e-d5ec-496f-88b4-3744f5b8ba80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='primary'])[2]</value>
      <webElementGuid>1fd1fec8-a6b0-40d5-9dee-baf176f77245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>0b9ca1d3-f6a2-48e3-b5ef-45b531b3b757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحميل الملف'])[1]/following::button[1]</value>
      <webElementGuid>b096a4d5-b330-4af5-bcb8-1a96e3c8f136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحميل'])[2]/following::button[2]</value>
      <webElementGuid>28a32981-1213-4d6d-8f40-b62296a6f578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رياضيات - علمي - فصل أول - 2007'])[2]/preceding::button[1]</value>
      <webElementGuid>88181ed9-28f9-4d2d-86b8-05effc031070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسامة العكور'])[3]/preceding::button[1]</value>
      <webElementGuid>e60e8b85-eee1-4b4a-b943-e40d974486df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='نشر']/parent::*</value>
      <webElementGuid>f966b273-c93b-4cb9-ba97-f5fc8d6488a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>432a9a22-ce8a-41d7-af7b-2fda81541f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'primary' and (text() = 'نشر' or . = 'نشر')]</value>
      <webElementGuid>6b5a302b-36b0-48cc-a441-03f9bafab051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
