<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2008     100     EN      20072008200920_cdb394</name>
   <tag></tag>
   <elementGuidId>14db9c60-ba4d-466a-ab7c-6539233e869e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd3d9284-7be5-492f-97df-ff607b5c0081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>179faa55-f439-46bc-ba7a-4f1c1ad4969a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]</value>
      <webElementGuid>08ee1154-26b1-4f7a-9305-06730d892def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>توجيهي2008 كل موادك الوزارية  بـ100 دينار فقطمدرستناأخبارناالامتحانات الإلكترونيةكن مندوبنامكتباتبرنامج التوجيهيENدخولتسجيلجو أكاديمي الصفحة الرئيسيةاختر صفك من هنا2007200820092006توجيهي 2007توجيهي 2008توجيهي 2009تكميلي 2006الدوراتبكجات وعروضالملفاتمنح جو اكاديميمعلمونشبابيكالمدرسة الالكترونيةفعاليات جو اكاديميتذييل جو أكاديميروابط سريعةالدوراتشبابيكمدرستنامعلمونالملفاتمنح جواكاديميكن مندوبنابكجات وعروضالدعمالمساعدةتواصل مع الدعم الفنيتواصل مع الدعم الفنيأخبارنامن نحنمكتباتالشروط والاحكامسياسة الخصوصيةحمل تطبيق الهاتف المحمول لجو اكاديمي على موبايلكتنزيل منApp Storeاحصل عليه منGoogle Playاحصل عليه منAppGalleryحمل برنامج سطح المكتب لجو اكاديمي على جهازكالتطبيق لنظامMACالتطبيق لنظامWINDOWSصفحاتنا على مواقع التواصل الاجتماعيجميع الحقوق محفوظة © لجواكاديمي 2024</value>
      <webElementGuid>19f99eac-cdee-473d-aef1-d68e4b2373bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]</value>
      <webElementGuid>0ec9ff2c-7326-4248-aa4b-314ea683fc33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div</value>
      <webElementGuid>9b81c9ef-ae68-4937-967b-d55840718957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>37c801e6-a4f3-4489-a6d1-19ac61e9df09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'توجيهي2008 كل موادك الوزارية  بـ100 دينار فقطمدرستناأخبارناالامتحانات الإلكترونيةكن مندوبنامكتباتبرنامج التوجيهيENدخولتسجيلجو أكاديمي الصفحة الرئيسيةاختر صفك من هنا2007200820092006توجيهي 2007توجيهي 2008توجيهي 2009تكميلي 2006الدوراتبكجات وعروضالملفاتمنح جو اكاديميمعلمونشبابيكالمدرسة الالكترونيةفعاليات جو اكاديميتذييل جو أكاديميروابط سريعةالدوراتشبابيكمدرستنامعلمونالملفاتمنح جواكاديميكن مندوبنابكجات وعروضالدعمالمساعدةتواصل مع الدعم الفنيتواصل مع الدعم الفنيأخبارنامن نحنمكتباتالشروط والاحكامسياسة الخصوصيةحمل تطبيق الهاتف المحمول لجو اكاديمي على موبايلكتنزيل منApp Storeاحصل عليه منGoogle Playاحصل عليه منAppGalleryحمل برنامج سطح المكتب لجو اكاديمي على جهازكالتطبيق لنظامMACالتطبيق لنظامWINDOWSصفحاتنا على مواقع التواصل الاجتماعيجميع الحقوق محفوظة © لجواكاديمي 2024' or . = 'توجيهي2008 كل موادك الوزارية  بـ100 دينار فقطمدرستناأخبارناالامتحانات الإلكترونيةكن مندوبنامكتباتبرنامج التوجيهيENدخولتسجيلجو أكاديمي الصفحة الرئيسيةاختر صفك من هنا2007200820092006توجيهي 2007توجيهي 2008توجيهي 2009تكميلي 2006الدوراتبكجات وعروضالملفاتمنح جو اكاديميمعلمونشبابيكالمدرسة الالكترونيةفعاليات جو اكاديميتذييل جو أكاديميروابط سريعةالدوراتشبابيكمدرستنامعلمونالملفاتمنح جواكاديميكن مندوبنابكجات وعروضالدعمالمساعدةتواصل مع الدعم الفنيتواصل مع الدعم الفنيأخبارنامن نحنمكتباتالشروط والاحكامسياسة الخصوصيةحمل تطبيق الهاتف المحمول لجو اكاديمي على موبايلكتنزيل منApp Storeاحصل عليه منGoogle Playاحصل عليه منAppGalleryحمل برنامج سطح المكتب لجو اكاديمي على جهازكالتطبيق لنظامMACالتطبيق لنظامWINDOWSصفحاتنا على مواقع التواصل الاجتماعيجميع الحقوق محفوظة © لجواكاديمي 2024')]</value>
      <webElementGuid>a6d39e4f-9080-4e25-96f1-8b5375127229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
