<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2</name>
   <tag></tag>
   <elementGuidId>7b73e9f2-0a7d-4cec-bdfa-f39801251fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.semi-bold.tw-text-sm.tw-opacity-90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/ol/li/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3f2d28d-5af6-4529-93dd-66aeceae3812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-text-sm tw-opacity-90</value>
      <webElementGuid>c6729f59-f489-406e-8206-e971d1a04425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تم نسخ رابط الملف</value>
      <webElementGuid>b43c0404-3074-49bd-b973-ee70d023b165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/ol[@class=&quot;tw-fixed tw-top-0 tw-z-[35000000] tw-flex tw-max-h-screen tw-w-full tw-flex-col-reverse tw-p-4 sm:tw-bottom-0 sm:tw-right-0 sm:tw-top-auto sm:tw-flex-col md:tw-max-w-[420px]&quot;]/li[@class=&quot;tw-group tw-pointer-events-auto tw-relative tw-flex tw-w-full tw-items-center tw-justify-between tw-space-x-4 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-p-6 tw-pr-8 tw-shadow-lg tw-transition-all data-[swipe=cancel]:tw-translate-x-0 data-[swipe=end]:tw-translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:tw-translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:tw-transition-none data-[state=open]:tw-animate-in data-[state=closed]:tw-animate-out data-[swipe=end]:tw-animate-out data-[state=closed]:tw-fade-out-80 data-[state=closed]:tw-slide-out-to-right-full data-[state=open]:tw-slide-in-from-top-full data-[state=open]:sm:tw-slide-in-from-bottom-full dark:tw-border-slate-800 tw-destructive tw-group tw-border-[#00CE7C] tw-bg-[#00CE7C] tw-text-slate-50 dark:tw-border-[#00CE7C] dark:tw-bg-[#00CE7C] dark:tw-text-slate-50&quot;]/div[@class=&quot;tw-grid tw-gap-1 tw-text-start&quot;]/div[@class=&quot;semi-bold tw-text-sm tw-opacity-90&quot;]</value>
      <webElementGuid>263f8864-6a2e-4e49-a80c-501a46270676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/ol/li/div/div</value>
      <webElementGuid>74520ed9-6156-4cf9-bd60-7cee2172cf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[9]</value>
      <webElementGuid>a0aa3a10-76ff-4f9b-800e-50ad1e889a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::div[10]</value>
      <webElementGuid>18f77a8d-b6e8-47b1-a7f9-77c61971303f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكل'])[1]/preceding::div[5]</value>
      <webElementGuid>19705696-d230-41bf-82ba-d026eb747fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج التوجيهي و الثانوي'])[2]/preceding::div[7]</value>
      <webElementGuid>07d54318-3ecc-452d-8bc1-1c213fabb276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تم نسخ رابط الملف']/parent::*</value>
      <webElementGuid>1416903a-f5dc-4765-aab9-36a1e33c15f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>8b1b66f9-21af-46c9-a845-0f8fec056f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'تم نسخ رابط الملف' or . = 'تم نسخ رابط الملف')]</value>
      <webElementGuid>a7aa7335-ec83-402e-810f-3525d3962ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
