<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-download-2-line tw-text-16px hovertw-_12563d</name>
   <tag></tag>
   <elementGuidId>592e8d95-b875-4757-8158-ee41eed19dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div[2]/button/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3acb059d-aa9d-4947-9b9b-85699fe4f627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-download-2-line tw-text-[16px] hover:tw-fill-white</value>
      <webElementGuid>94b6343f-4bbd-44e9-88d2-f8f40c6cc9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;md:tw-p-5&quot;]/div[@class=&quot;tw-mt-2&quot;]/div[@class=&quot;tw-relative tw-top-[-4px] tw-pt-8&quot;]/div[@class=&quot;ant-col ant-col-rtl css-14i19y2&quot;]/div[@class=&quot;ant-row ant-row-center ant-row-middle ant-row-rtl  shared_full-width__6Fhsp css-14i19y2&quot;]/div[@class=&quot;ant-spin-nested-loading css-14i19y2&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-row ant-row-rtl css-14i19y2&quot;]/div[@class=&quot;shared_full-width__6Fhsp shared_margin-column-half-rem__cGLZG&quot;]/div[@class=&quot;tw-mb-4  tw-rounded-xl tw-border tw-border-gray-100 tw-bg-white tw-px-10 tw-py-8 tw-transition-all tw-duration-300 hover:tw-shadow-md sm:tw-mb-0 sm:tw-px-6 sm:tw-py-4 tw-cursor-pointer&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-between sm:tw-items-center md:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-end tw-justify-center tw-gap-4&quot;]/div[@class=&quot;tw-w-full tw-text-[12px] tw-font-semibold md:tw-w-fit&quot;]/div[@class=&quot;tw-flex tw-h-full tw-w-full tw-items-center tw-justify-end tw-gap-3 tw-text-[12px] tw-font-semibold tw-text-gray-500 sm:tw-mt-3&quot;]/div[@class=&quot;tw-me-2 !tw-w-[130px]&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorDarkblue__SQifS tw-rounded-[10px] tw-cursor-pointer !tw-h-[44px] !tw-w-[140px]&quot;]/div[@class=&quot;tw-flex !tw-h-[44px] tw-items-center tw-justify-center&quot;]/i[@class=&quot;ri-download-2-line tw-text-[16px] hover:tw-fill-white&quot;]</value>
      <webElementGuid>3ba2eda9-124d-4c82-a770-251e1748698a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div[2]/button/div/i</value>
      <webElementGuid>1b1d7280-5f04-4434-b4df-0b31dbba0ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/i</value>
      <webElementGuid>d1add91e-bee7-40bd-ad2f-f2b7bc89c42e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
