<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>c61c8282-e08a-4d07-93e5-1891408c342a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>65a39e32-b4f1-4ca0-ae19-f826f88639b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-mb-2 tw-text-[14px] tw-font-semibold sm:tw-text-[18px]</value>
      <webElementGuid>c969d0bf-1eec-4833-8ea3-1db214925209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مقدمة التكامل والقواعد الجزء الاول والثاني.</value>
      <webElementGuid>d45870a8-32ac-4eee-80a4-77a876d655b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;md:tw-p-5&quot;]/div[@class=&quot;tw-mt-2&quot;]/div[@class=&quot;tw-relative tw-top-[-4px] tw-pt-8&quot;]/div[@class=&quot;ant-col ant-col-rtl css-14i19y2&quot;]/div[@class=&quot;ant-row ant-row-center ant-row-middle ant-row-rtl  shared_full-width__6Fhsp css-14i19y2&quot;]/div[@class=&quot;ant-spin-nested-loading css-14i19y2&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-row ant-row-rtl css-14i19y2&quot;]/div[@class=&quot;shared_full-width__6Fhsp shared_margin-column-half-rem__cGLZG&quot;]/div[@class=&quot;tw-mb-4  tw-rounded-xl tw-border tw-border-gray-100 tw-bg-white tw-px-10 tw-py-8 tw-transition-all tw-duration-300 hover:tw-shadow-md sm:tw-mb-0 sm:tw-px-6 sm:tw-py-4 tw-cursor-pointer&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-between sm:tw-items-center md:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-start tw-gap-6 sm:tw-gap-4&quot;]/div[2]/p[@class=&quot;tw-mb-2 tw-text-[14px] tw-font-semibold sm:tw-text-[18px]&quot;]</value>
      <webElementGuid>c0db9e6b-2072-4bc7-b22d-f645df53e442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>e21f67b4-c8bb-435f-9bca-fe831c1cb1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكل'])[1]/following::p[1]</value>
      <webElementGuid>84fa0c39-6990-40a3-b5b7-d79da56ab579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نوع الملف:'])[1]/following::p[1]</value>
      <webElementGuid>7f1eefda-8b25-4ea6-b43c-2762e0d5f2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رياضيات - علمي - فصل أول - 2007'])[1]/preceding::p[1]</value>
      <webElementGuid>73887073-5af8-4999-8ee9-b0df93b3ea71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسامة العكور'])[2]/preceding::p[1]</value>
      <webElementGuid>47283d6b-f02a-4534-9ed2-d4be5c078b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مقدمة التكامل والقواعد الجزء الاول والثاني.']/parent::*</value>
      <webElementGuid>d279cc06-3e42-410e-a01d-b4e013275f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>2379480b-e25a-4c83-b38c-85b5dde3eb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'مقدمة التكامل والقواعد الجزء الاول والثاني.' or . = 'مقدمة التكامل والقواعد الجزء الاول والثاني.')]</value>
      <webElementGuid>7be7d41f-280b-43d7-8fae-4ef16e640e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
