<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>e6baa10f-df6f-48c3-aea6-7c3cdc181105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer-card']/div[2]/div/div[2]/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a551358-a0a0-445a-9af2-ee9717f32046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>اذهب الى  الشروط والاحكام | جو اكاديمي</value>
      <webElementGuid>625a856b-972a-4599-bba3-7adbd559dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> semi-bold tw-text-center tw-text-[16px] tw-text-brand-light-grey  md:tw-text-start</value>
      <webElementGuid>a53f8526-9f83-4ce3-a21f-180c72763d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/terms-and-conditions</value>
      <webElementGuid>8de38756-ee7d-499c-a259-70405dae3df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الشروط والاحكام</value>
      <webElementGuid>3edae8d1-7c2e-4458-86cc-204ce3aab512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-card&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-justify-between lg:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-w-full tw-grid-cols-2 tw-flex-col tw-justify-between md:tw-grid&quot;]/div[@class=&quot;tw-mx-0 tw-my-8 tw-flex tw-flex-col tw-gap-4&quot;]/a[@class=&quot;semi-bold tw-text-center tw-text-[16px] tw-text-brand-light-grey  md:tw-text-start&quot;]</value>
      <webElementGuid>56209137-e3e5-4d65-914a-92416e3b316b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer-card']/div[2]/div/div[2]/a[5]</value>
      <webElementGuid>01851309-a13d-4bc3-8d12-db0ad2725b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'الشروط والاحكام')]</value>
      <webElementGuid>d0f03db3-c1f6-4aba-aca5-6063b9a6846f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مكتبات'])[2]/following::a[1]</value>
      <webElementGuid>eabbffa3-7b3c-4988-8811-50f43c9ec1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='من نحن'])[1]/following::a[2]</value>
      <webElementGuid>9bf91c12-c9d9-454c-b834-c6bc7e1e2ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سياسة الخصوصية'])[1]/preceding::a[1]</value>
      <webElementGuid>ef84daf5-a22b-4fb0-8a1c-46e99b2d2b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حمل تطبيق الهاتف المحمول لجو اكاديمي على موبايلك'])[1]/preceding::a[2]</value>
      <webElementGuid>84daae2a-6968-41c3-bfb5-84f2e9ab6e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الشروط والاحكام']/parent::*</value>
      <webElementGuid>c703e475-0ccb-47f5-ac89-f7aec2db1304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/terms-and-conditions')]</value>
      <webElementGuid>90af81e2-4417-4959-a04d-224d45cc5305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[5]</value>
      <webElementGuid>582b70e6-390f-42b0-b30a-38cc6a856f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/terms-and-conditions' and (text() = 'الشروط والاحكام' or . = 'الشروط والاحكام')]</value>
      <webElementGuid>d80b12b0-f895-4d85-bd39-8e9f2e398b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
